Build realizado en local
luislealdev/herramientas-tic pull request #24
Opened 2024-12-12 17:51 UTC by avilaYael

Me parece que todavía no ha sido resuelto el responsive de las tablas de admin, así que me voy a encargar mientras de eso.

2024-12-14 21:16 UTC, luislealdev commented on src/actions/tools/get-paginated-tools.ts
> +            take: take === -1 ? undefined : take,
¿Por qué agregaste esta condicional?

2024-12-14 21:17 UTC, luislealdev commented on src/components/admin/dashboard/Dashboard.tsx
> +  const itemsPerPage = -1;
Cualquier cosa que tenga que ver con números negativos ya me da cosita jajajaja, podrías explicarme este código?

2024-12-14 21:17 UTC, luislealdev commented on src/components/admin/dashboard/Dashboard.tsx
> +        console.log('Logs cargados:', fetchedLogs); // Ver los logs en la consola
Cualquier console.log del lado del cliente deberá de ser eliminado.

2024-12-14 21:18 UTC, luislealdev requested changes
Te puse algunos comentarios, sobre todo me gustaría entender bien sobre la agregación de condicionales con números negativos y el uso de los mismos.

2024-12-14 22:47 UTC, avilaYael commented
Desde que cristian menciono que en el dashboard aparecia que teniamos 10 herramientas, ocupaba anexar una condicion la cual mandara a llamar el numero total de herramientas, prisma maneja el -1 como indefinido y eso hace que la condicion pueda extraer no solo 10 para la paginacion. Intente otras opciones en lugar del negativo pero no compilaba correctamente

2024-12-16 12:09 UTC, luislealdev approved these changes

2024-12-16 12:09 UTC, merged